services:
  db:
    image: postgres:16
    container_name: jota_db
    environment:
      POSTGRES_USER: jota
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: jota_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
